name: extraction stage 2 CI/CD

on:
  push:
    branches: [ main ]

jobs:
  builddocker:
    name: Build docker image and publish to ECR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Log into Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and publish image to ECR
        env:
          ECR_REGISTRY: 817774243452.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: extraction-stage-2
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . --platform linux/amd64
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
